### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by chenchengyin** [ChinaStyle812/AssetsRefGenerator#1]
1、自动生成的res.dart，建议放到generated目录下，放在根目录太不美观了。
2、添加图片后，好像并没有在pubspec.yaml中同时添加图片声明

**Comment by AndrewShen812** [comment]
首先非常感谢你的建议，我会加以考虑的。由于这是一个没有强制开发规范约束的个人项目，产品也会体现开发者的一些个人理念，和在经验丰富的同行看来是低水平的表现，感谢你的理解和包容。
