### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by renygit** [ChinaStyle812/AssetsRefGenerator#14]
1.希望写入pubspec.yaml时，- assets/images/这样即可，不用- assets/images/xx.png，同时保持文件的原有编码方式。
2.生成的字段名驼峰命名
3.生成的文件、类名和路径位置可以自定义

**Comment by AndrewShen812** [comment]
谢谢你的建议，终于又有时间维护一下这个项目。
你建议的这些功能已经开发完毕，将在1.2.0版本中呈现，欢迎你继续使用。以下是设置页面预览：
![Plugin settings](https://andrewshen812.github.io/AssetRefGenerator/PluginSettings.png)
