### ISSUE TITLE
After upgrading Flutter 3.3.6, Android Studio can't finish normally.

### ISSUE THREAD

**Issue by OctMon** [ChinaStyle812/AssetsRefGenerator#17]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/17644890/200218575-7b70b718-40a1-44b4-bc32-b97e3ffffb25.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/17644890/200218911-0fa44da7-5427-4899-aefe-0f9d7e22d2e4.png">

[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.3.6 on channel stable at
      /Users/limeng/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (12 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

**Comment by juanxme** [comment]
x2

**Comment by AndrewShen812** [comment]
will be fixed in v1.1.1

**Comment by rxvincent** [comment]
问题在Android Studio Flamingo 2022.2.1 Patch1 中再次出现。
加载了新的UI布局详见
https://stackoverflow.com/questions/74685382/how-to-enable-android-studio-new-ui
