### ISSUE TITLE
关于pubspec.yaml文件的改进建议

### ISSUE THREAD

**Issue by Iridescentangle** [ChinaStyle812/AssetsRefGenerator#22]
请问是否可以增加【不对每个资源文件的罗列】这样的选项支持呢？例如assets/images目录下有abc三张png文件，其实只要配置assets/images就好了，这样全部列出来在资源较多的情况下会有很多行

**Comment by LiJoeAllen** [comment]
pubspec.yaml中删掉不要的不久好了？

**Comment by Iridescentangle** [comment]
> pubspec.yaml中删掉不要的不久好了？

手动删掉当然可以，但是之后再添加，还会重新生成呀

**Comment by LiJoeAllen** [comment]
提交你的想法的代码呗，或者那就换个插件，插件多着呢

**Comment by Iridescentangle** [comment]
> 提交你的想法的代码呗，或者那就换个插件，插件多着呢

呃呃，您现在是这个项目的维护者吗？
