### ISSUE TITLE
自动化打包

### ISSUE THREAD

**Issue by SunStarJ** [ChinaStyle812/AssetsRefGenerator#7]
您好如果我想使用自动化打包的话,有什么命令可以代替手动生成么

**Comment by AndrewShen812** [comment]
很遗憾，因为这是一个和开发IDE强关联的辅助类工具插件，所以目前还没有可替代手动生成的调用方式。

而且我不确定你说的自动化打包，使用的具体环境。有兴趣的话，欢迎你仔细描述一下。如果可能后续我会考虑扩展该功能的。

**Comment by AndrewShen812** [comment]
The function described in this issue should be implemented by the build system, such as a gradle plugin, instead of a IDE plugin.
