### ISSUE TITLE
请问是否支持命令行呢？

### ISSUE THREAD

**Issue by Iridescentangle** [ChinaStyle812/AssetsRefGenerator#9]
当项目中Flutter以FlutterModule形式引入时，菜单点击生成失败

**Comment by AndrewShen812** [comment]
> 1、是否支持命令行?

不支持，因为本插件的定位是IDE插件。能支持命令行的，都是通过构建系统而非IDE来扩展的，例如gradle 插件。

> 2、当项目中Flutter以FlutterModule形式引入时，菜单点击生成失败

这个确实是本插件目前没有覆盖到的使用场景，下个版本我会考虑支持的，感谢反馈。

**Comment by Iridescentangle** [comment]
> > 1、是否支持命令行?
> 
> 不支持，因为本插件的定位是IDE插件。能支持命令行的，都是通过构建系统而非IDE来扩展的，例如gradle 插件。
> 
> > 2、当项目中Flutter以FlutterModule形式引入时，菜单点击生成失败
> 
> 这个确实是本插件目前没有覆盖到的使用场景，下个版本我会考虑支持的，感谢反馈。

好的,非常感谢,加油💪🏻
